---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-read-queue
  labels:
    rbac.kyverno.io/aggregate-to-admission-controller: "true"
    rbac.kyverno.io/aggregate-to-background-controller: "true"
    rbac.kyverno.io/aggregate-to-reports-controller: "true"
rules:
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - workloads
  - workloads/status
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - customruns
  - customruns/status
  verbs:
  - list
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-manage-queue
  labels:
    rbac.kyverno.io/aggregate-to-admission-controller: "true"
    rbac.kyverno.io/aggregate-to-background-controller: "true"
rules:
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - workloads
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - update
- apiGroups:
  - tekton.dev
  resources:
  - customruns
  - customruns/status
  verbs:
  - list
  - get
  - watch
  - update
  - patch
